app:
 ms:
  percentage:
   url: http://localhost:8081/tenpo
server:
 servlet:
  context-path: /tenpo
resilience4j:
 retry:
  configs:
   default:
    maxAttempts: 3
    waitDuration: 1s
    enableExponentialBackoff: true
    exponentialBackoffMultiplier: 2
  instances:
   percentageClient:
    baseConfig: default
    ignoreExceptions:
     - io.github.resilience4j.circuitbreaker.CallNotPermittedException
 circuitbreaker:
  instances:
   percentageClient:
    registerHealthIndicator: true
    slidingWindowSize: 10
    minimumNumberOfCalls: 5
    permittedNumberOfCallsInHalfOpenState: 3
    waitDurationInOpenState: 10s
    failureRateThreshold: 50
    eventConsumerBufferSize: 10
    automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
   instances:
    percentageClient:
     timeoutDuration: 2s
feign:
 circuitbreaker:
  enabled: true
management:
 endpoint:
  health:
   show-details: always
 security:
  enabled=false:
 endpoints:
  web:
   exposure:
    include: health,info,retries,retryevents
 health:
  circuitbreakers:
   enabled: true
  retries:
   enabled: true
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: root
  password: root
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
 cache:
  type: redis
  redis:
   time-to-live: 30
 main:
  allow-bean-definition-overriding: true
 profiles:
  active: development
 data:
  redis:
   host: localhost
   port: 6379